<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Net.Web.Api.Sdk.Web.Examples</RootNamespace>
    <AssemblyName>Net.Web.Api.Sdk.Web.Examples</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DocumentationFile>doc-api-sdk-example.xml</DocumentationFile>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Net.Web.Api.Sdk\Net.Web.Api.Sdk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="App_Data\Certficates\net-web-api-jwt-signing.pfx" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="App_Data\Certficates\net-web-api-jwt-validating.cer" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
