<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <DocumentationFile>Documentation\Swagger\Resources\doc-api-sdk.xml</DocumentationFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="ByteSize" Version="2.1.1" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.5" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.9.0" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="8.9.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.3.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="7.3.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.5" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.9.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Documentation\Swagger\Resources\SwaggerConfigurationSdk.json" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\index.html" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\logo-16x16.png" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\logo-32x32.png" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\swagger-ui-override.css" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\swagger-ui-override.js" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\swagger.html" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\doc-api-sdk.xml" />
    <EmbeddedResource Include="Security\Resources\token-sdk.config" />
  </ItemGroup>
</Project>
